WIP > Add support for passing repetition number to RunnerFunc() and the "Index()" benchmark

diff --git a/_benchmarks/scripts/run-benchmarks b/_benchmarks/scripts/run-benchmarks
--- a/_benchmarks/scripts/run-benchmarks
+++ b/_benchmarks/scripts/run-benchmarks
@@ -18,8 +18,8 @@ if [[ -z $ELASTICSEARCH_REPORT_URL ]]; then
   echo -e "\033[31;1mERROR:\033[0m Required environment variable [ELASTICSEARCH_REPORT_URL] not set\033[0m"; exit 1
 fi
 
-if [[ -z $SOURCE_DATA ]]; then
-  echo -e "\033[31;1mERROR:\033[0m Required environment variable [SOURCE_DATA] not set\033[0m"; exit 1
+if [[ -z $DATA_SOURCE ]]; then
+  echo -e "\033[31;1mERROR:\033[0m Required environment variable [DATA_SOURCE] not set\033[0m"; exit 1
 fi
 
 TIMEFORMAT="(Duration: %0lR)"
